const METHODS = [
  { name: "TOTP (Authenticator apps)", desc: "Time-based one-time codes generated by an app (Google Authenticator, Authy). No network dependency, phishing-resistant relative to SMS.", security: "Good" },
  { name: "SMS codes", desc: "Code sent via text message. Convenient but vulnerable to SIM-swapping attacks — no longer recommended as a sole second factor for sensitive accounts.", security: "Weak" },
  { name: "Push notifications", desc: "App sends a push asking to approve/deny a login. User-friendly, but vulnerable to 'MFA fatigue' attacks (spamming approval requests).", security: "Good" },
  { name: "Hardware security keys (FIDO2/WebAuthn)", desc: "Physical device (YubiKey etc.) or platform authenticator. Phishing-resistant — the strongest widely available option.", security: "Best" },
  { name: "Backup codes", desc: "Single-use codes generated in advance for account recovery — not a primary factor, but essential as a fallback.", security: "N/A (recovery)" },
];

export default function TwoFactorReference() {
  return (
    <div className="space-y-2">
      {METHODS.map((m) => (
        <div key={m.name} className="bg-slate-100 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg p-4">
          <div className="flex justify-between items-start">
            <p className="text-sm font-medium text-emerald-600 dark:text-emerald-400">{m.name}</p>
            <span className="text-xs text-slate-500 dark:text-slate-500">{m.security}</span>
          </div>
          <p className="text-sm text-slate-700 dark:text-slate-300 mt-1">{m.desc}</p>
        </div>
      ))}
    </div>
  );
}
